# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Chandana Velaga
tagline:          'Resume'
description:      'Product Enthusiast<br>Ex-Cisco | NITK Surathkal<br>Connect @ <a href="https://www.linkedin.com/in/chandana-velaga-bb17b6102/" target="_blank">linkedin</a>'
# url:              https://chandanavelaga.github.io/
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/chandanavelaga/chandanavelaga.github.io

github: [metadata]

plugins:
  - jemoji