# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Chandana Velaga
tagline:          'Resume'
description:      '<a href="https://www.linkedin.com/in/chandana-velaga-bb17b6102/" target="_blank">@ linkedin</a>'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Chandana Velaga'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/chandanavelaga/chandanavelaga.github.io
